package com.example.handyapp.navigation

sealed class Screen(val route: String) {
    //   object Jobs: Screen(route = "home_screen/{id}")
    object Jobs: Screen(route = "Jobs")
    object Login: Screen(route = "login_screen")
    object Register: Screen(route = "register_screen")
    object RegisterInfo: Screen(route = "register_info_screen")
    object RegistrationSucceeded: Screen(route = "registration_succeeded_screen")
    object Waiting: Screen(route = "waiting_screen")
    object MyRequests: Screen(route = "My Requests")
    object DetailRequest: Screen(route = "Detail Request")
    object MyTasks: Screen(route = "My Tasks")
    // object TasksDetails: Screen(route = "TasksDetails")
    object ReportScreen: Screen(route = "ReportScreen")
    object Notifications: Screen(route = "Notifications")
    object Settings: Screen(route = "Settings")
    object Refused: Screen(route = "refused")
    object OneLastStepScreen: Screen(route = "One last step")
    object FinalRegistrationScreen: Screen(route = "Final registration")
    object FinishedSetupScreen: Screen(route = "Finished setup")
    object BrowseJobsScreen: Screen (route = "jobs_screen")
    object JobsDetails: Screen (route = "jobs_details_screen")
    object BidScreen: Screen (route = "bid_screen")
    object ChatScreen: Screen (route = "chat_screen")
    object NotificationScreen: Screen (route = "Notification")
    object MapScreen: Screen (route = "Map")
    object Blocked: Screen (route = "Banned")
    object ProfileSettings: Screen (route = "Profile")
    object SavedJobs: Screen (route = "Saved Jobs")
}